package pubresolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/azarc-io/verathread-gateway/internal/gql/graph/common/model"
	pubgraph "github.com/azarc-io/verathread-gateway/internal/gql/graph/public"
	"github.com/azarc-io/verathread-next-common/common/genericdb"
)

// RegisteredApps is the resolver for the registeredApps field.
func (r *queryResolver) RegisteredApps(ctx context.Context, page genericdb.Page, where *model.RegisteredAppsWhereRules, sort *model.RegisteredAppsSort) (*model.RegisteredAppsPage, error) {
	panic(fmt.Errorf("not implemented: RegisteredApps - registeredApps"))
}

// ShellConfiguration is the resolver for the shellConfiguration field.
func (r *queryResolver) ShellConfiguration(ctx context.Context, tenantID string) (*model.ShellConfiguration, error) {
	panic(fmt.Errorf("not implemented: ShellConfiguration - shellConfiguration"))
}

// Query returns pubgraph.QueryResolver implementation.
func (r *Resolver) Query() pubgraph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
