name: gw-dev

services:
  ##################################################################################
  # GLOBAL COMMON SERVICES
  ##################################################################################

  shell-fe:
    build:
      context: .
      dockerfile: "deployment/docker/web/Dockerfile.dev"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      VERSION: 1
    volumes:
      - ./cmd/web:/src

  example-fe:
    build:
      context: .
      dockerfile: "example/docker/web/Dockerfile.dev"
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    volumes:
      - ./example/web:/src

  gateway:
    build:
      context: .
      dockerfile: "deployment/docker/app/Dockerfile.dev"
      args:
        GITHUB_PAT_TOKEN: ${GITHUB_PAT_TOKEN}
    environment:
      CONFIG_DIR: cmd/app/config
      BASE_CONTEXT: base
      CONFIG_CONTEXTS: docker
    ports:
      - "6010:6010"
      - "6011:6011"
    depends_on:
      - mongodb
      - keydb
      - nats
    volumes:
      - ./internal:/src/internal
      - ./cmd/app:/src/cmd/app
      - ./go.mod:/src/go.mod
      - ./go.sum:/src/go.sum

  example:
    build:
      context: .
      dockerfile: "example/docker/app/Dockerfile.dev"
      args:
        GITHUB_PAT_TOKEN: ${GITHUB_PAT_TOKEN}
    environment:
      CONFIG_DIR: /src/example/app/config
      BASE_CONTEXT: docker
    ports:
      - "6110:6110"
      - "6111:6111"
    depends_on:
      - gateway
    volumes:
      - ./example/app:/src/example/app
      - ./go.mod:/src/go.mod
      - ./go.sum:/src/go.sum
