services:
  ##################################################################################
  # GLOBAL COMMON SERVICES
  ##################################################################################

  shell-fe:
    build:
      context: .
      dockerfile: "deployment/docker/web/Dockerfile.dev"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      VERSION: 1
    volumes:
      - ./cmd/web:/src

  example-fe:
    build:
      context: .
      dockerfile: "example/docker/web/Dockerfile.dev"
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    volumes:
      - ./example/web:/src

  gateway:
    image: ghcr.io/azarc-io/verathread-gateway/gateway-be:RPP-6-315-100c87b1
    environment:
      CONFIG_DIR: /config
      BASE_CONTEXT: base
      CONFIG_CONTEXTS: metalogix
      AUTH_DOMAIN: ${AUTH_DOMAIN}
      BIND_ADDRESS: 0.0.0.0
    volumes:
      - ./cmd/app/config:/config
    ports:
      - "6010:6010"
    depends_on:
      - mongodb_dev
      - keydb
      - nats

  example:
    image: ghcr.io/azarc-io/verathread-gateway/gateway-be-example:v1.51.2-linux-arm64
    environment:
      CONFIG_DIR: /config
      BASE_CONTEXT: metalogix
    volumes:
      - ./example/app/config:/config
    ports:
      - "6110:6110"
    depends_on:
      - gateway
