apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vth-cloud-org-stream
  namespace: vth-next
spec:
  type: pubsub.az.jetstream.stream
  version: v1
  metadata:
    - name: natsURL
      secretKeyRef:
        name: NATS_ADDRESS
        key: NATS_ADDRESS
    - name: streamName
      value: "ORGANIZATION"
    - name: subjects
      value: "org.v1.>"
    - name: deliverPolicy
      value: new
    - name: queueGroupName
      value: "org-events"
auth:
  secretStore: secrets-store
