FROM node:20
WORKDIR /src
ENV VER=3
ADD example/web/package.json package.json
ADD example/web/yarn.lock yarn.lock
RUN yarn install
RUN yarn global add @rsbuild/core

ENTRYPOINT yarn dev --env-mode development
