import Head from "next/head";
import styles from "@/styles/Home.module.css";
import useFederatedComponent from "@/helpers";

export default function Home() {
    const { Component, isError } = useFederatedComponent({
        remoteUrl: 'http://localhost:3001/_next/static/runtime/remoteEntry.js',
        moduleToLoad: './Counter',
        remoteName: 'example',
    });

    if (isError) return <div>Error loading remote component</div>;

    return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.description}>
            {Component ? <Component/> : null}
        </div>
      </main>
    </>
  );
}
