{{- if .Values.secret }}
{{- if .Values.local }}
apiVersion: v1
kind: Secret
metadata:
  name: nats-custom-conf
type: Opaque
data:
  accounts.conf: {{ .Values.secret.accounts }}
{{- else }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nats-custom-conf
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    accounts.conf: {{ .Values.secret.accounts }}
{{- end }}
{{- end }}
