name: vth-gateway-example
id: vth-gateway-example-1
webDir: web/dist

logger:
  level: info
  mode: dev # or prd

dapr:
  http_port: 6112
  grpc_port: 6111

http:
  address: 0.0.0.0
  port: 6110

registration:
  webBaseUrl: http://example:6110
  baseWsUrl: ws://example:6110

# Enabled dapr in embedded mode, to only be used for local development
# in K8S dapr is automatically injected into the pod as a container and this is not required
development:
  enabled: true
  app_id: vth-gateway-example
  app_port: 6110
  grpc_port: 6111
  http_port: 6112
  metrics_port: 6113
  internal_grpc_port: 6114
  log_level: info
  placement_host: placement:50006
  config_file: ../dapr/config/config.yaml
