name: vth-gateway-example
id: vth-gateway-example-1
webDir: web/dist

logger:
  level: trace
  mode: dev # or prd

http:
  public:
    address: 0.0.0.0
    port: 6110
  private:
    address: 0.0.0.0
    port: 6111
  cors:
    allow_credentials: true
    allow_origins:
      - '*'
    allow_headers:
      - '*'
    allow_methods:
      - POST
      - GET
      - PUT
      - DELETE
      - PATCH
      - HEAD

registration:
  gateway_url: http://gateway:6011/graphql
  web_url: http://example-fe:3001
  api_url: http://example:6110/graphql
