{{- define "service-library-chart.service" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "service.fullname" . }}
spec:
  ports:
    - port: {{ .Values.bind.http }}
      name: http
  clusterIP: None
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
{{- end }}
