database:
  dsn: mongodb%3A%2F%2Fmongodb_dev%3A27017%2F%3FreplicaSet%3Drs0%26tls%3Dfalse%26connect%3Ddirect%26retryWrites%3Dtrue%26w%3Dmajority
  name: vth-gateway

nats:
  address: nats://nats:4222
  drain: true

redis:
  address: keydb:6379

http:
  public:
    address: 0.0.0.0
  private:
    address: 0.0.0.0

gateway:
  web_dir: "/web"
  web_proxy: ""

auth:
  domain: https://dev-iq3b9wdl.us.auth0.com
