name: vth-gateway
id: vth-gateway-1

logger:
  level: info
  mode: dev # or prd

database:
  host: ${MONGO_HOST}
  port: 27017
  user: ""
  pass: ""
  args: "?replicaSet=rs0&tls=false&connect=direct&retryWrites=true&w=majority"
  scheme: ""
  name: vth-gateway

redis:
  address: localhost:6379

nats:
  address: nats://localhost:4222
  drain: true

http:
  public:
    address: ${BIND_ADDRESS}
    port: 6010
  private:
    address: ${BIND_ADDRESS}
    port: 6011
  cors:
    allow_credentials: true
    allow_origins:
      - '*'
    allow_headers:
      - '*'
    allow_methods:
      - POST
      - GET
      - PUT
      - DELETE
      - PATCH
      - HEAD

gateway:
  web_dir: ${PROJECT_BASE_DIR}/cmd/web2/dist
  backoffice_org: org_hiUmCjtFR7ZgEckN
  metrics:
    address: ${BIND_ADDRESS}
    port: 6015
  services: []

cluster:
  enabled: true

auth:
  domain: ${AUTH_DOMAIN}
  jwt:
    auth_domain: https://auth.dev.cloud.azarc.dev
    aud: https://verathread.com/api/verify
    iss: https://dev-iq3b9wdl.us.auth0.com/
    claims: https://verathread.com/claims
