nats:
  volume:
    storageSize: 10Gi
    accessModes: ReadWriteOnce
  nats:
    config:
      - name: accounts
        secret:
          secretName: nats-custom-conf
    jetstream:
      domain: staging
      fileStorage:
        enabled: true
        size: 5Gi
  cluster:
    enabled: true
    replicas: 3
    noAdvertise: false
