{{- if .Values.configuration }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
    {{- end }}
data:
  # main config.yaml file
  config.yaml: |
  {{- tpl (.Values.configuration | toYaml | trim) $ | nindent 4}}
  {{- range $key, $value := .Values.extraConfiguration }}
  {{ $key }}: |
    {{- tpl $value $ | nindent 4 }}
  {{- end }}
{{- end -}}
