{{- $ingress := .Values.ingress }}
{{- if $ingress.enabled }}
apiVersion: {{ include "service.ingressAPIVersion" . }}
kind: Ingress
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  {{- with $ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
    {{- range $key, $value := $ingress.labels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
spec:
  rules:
    {{- range .Values.ingress.rules }}
    {{- $rule := . }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
            pathType: Prefix
            backend:
              service:
                name:  {{ tpl $rule.service $ | quote }}
                port:
                  name: {{ $rule.servicePort }}
            {{- else }}
            backend:
              serviceName: {{ include "service.fullname" $ }}
              servicePort: {{ $rule.servicePort }}
            {{- end }}
          {{- end }}
    {{- end }}
{{- end -}}
