{{- if .Values.secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.secrets }}
      {{ $key }}: {{ $value }}
    {{- end }}
  {{- end -}}
